# Generated by Django 4.2.6 on 2023-10-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numidusuario', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numidusuario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numventas', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'artista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('idcamiseta', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'camiseta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogocamiseta',
            fields=[
                ('idcatcamiseta', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cantdisponible', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'catalogocamiseta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogoestampa',
            fields=[
                ('idcatestampa', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cantdisponible', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'catalogoestampa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numidusuario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('direccion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estampa',
            fields=[
                ('idestampa', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=50)),
                ('imgurl', models.CharField(max_length=50)),
                ('disponible', models.BooleanField()),
                ('tema', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=6)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('numidartista', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'estampa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('numidcliente', models.DecimalField(decimal_places=0, max_digits=10)),
                ('preciototal', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(max_length=2)),
                ('numid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
